- name: pushing my.cnf
  template:
     src: my.cnf.j2
     dest: /etc/my.cnf

- name: restart mysqld
  service:
     name: mysqld
     state: restarted
  

- name: pushing mysqlconf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: pushing password
  template:
    src: passwd.j2
    dest: /root/.my.cnf
  

- name: stopping slave
  command: mysql -u root -e "stop slave"

- name: mysql-slave
  mysql_replication:
     mode: changemaster
     master_user: "{{ slave_user }}"
     master_host: "{{ master_ip }}"
     master_password: "{{ master_password }}"
     master_log_file: "{{ master_file }}"
     master_log_pos: "{{ master_position }}"


- name: starting slave
  command: mysql -u root -e "start slave"
  notify: restart mysqld
